### ISSUE TITLE
Support for Scala version 2.10.5

### ISSUE THREAD

**Issue by camspilly** [TrueCar/mleap#16]
Databricks currently only supports 2.10.5, can cross version support come to 2.10.5?

**Comment by hollinwilkins** [comment]
Hey camspilly,

We cross compile for 2.10.6, which should work fine with Spark on Scala 2.10. Have you had problems?

**Comment by eml2170** [comment]
Thanks for the quick reply. Yes but we figured it out. The netlib dependency doesn't build in databricks or with gradle - we had to exclude that and pull it in separately.

**Comment by hollinwilkins** [comment]
Great, please let me know how the rest of your experience goes with MLeap and please reach out to me if you have any questions :) I am going to close this ticket and add a new one to investigate the netlib dependency, which seems like there is something going on there that I am not aware of.
